# intentionally no language: Haskell
sudo: required
branches:
  only:
  - source
addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.2],sources: [hvr-ghc]}}
# addons:
#   apt:
#     sources:
#     - debian-sid
#     packages:
#     - libghc-hakyll-dev
git:
  submodules: false # Don't init and update the _site submodule automatically
before_install:
- export PATH=/opt/ghc/7.10.2/bin:/opt/cabal/1.22/bin:$PATH
- openssl aes-256-cbc -K $encrypted_9faceced67a1_key -iv $encrypted_9faceced67a1_iv -in travis_rsa.enc -out travis_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 travis_rsa
- ssh-add travis_rsa
- git submodule init
- git submodule update
install:
- sudo apt-get update
- sudo apt-get install libghc-hakyll-dev
script:
- cabal run site -- build
after_script:
- cd _site
- git status
- git diff -b
